### PR TITLE
skip env vars that are empty

### PR DESCRIPTION
**Pull request by cheops**

### CODE REVIEW

**Comment by kdschlosser** [comment]
Just out question does it really matter if the variables are empty? I am not sure what variables have been set that are empty but if they are set by ESPIDF they they are used whether or not they are empty. The idea is to make the environment exactly as the ESPIDF sets it up as. That would include any empty environment variables as well. It is only making a copy of what is seen is all it is doing. 

I am just asking a question as I have not checked to see what the environment looks like. If there is an issue caused by the empty variables we need to know the source of the empty variables as they may not be from the ESPIDF getting set up.

Making a copy of os.environ and then checking for missing/different variables might be a better solution to do. I know that when a subprocess is created and "None" is passed as the environment then the subprocess modules will use the current environment when running the subprocess. so when using printenv in a subprocess should produce exactly what is in os.environ.

**Comment by cheops** [comment]
I run the make script under WSL (Ubuntu) and the environment variable WSLENV is empty
`prompt$` ` python3 make.py esp32 mpy_cross submodules clean BOARD=ESP32_GENERIC BOARD_VARIANT=SPIRAM`

when the build script runs these commands:
`[['cd', 'lib/esp-idf'], ['. ./export.sh'], ['printenv']]`
This is the error:
```
WSL2_GUI_APPS_ENABLED=1
HOSTTYPE=x86_64
WSLENV=
/bin/sh: 22: ./export.sh: [[: not found
Not using an unsupported version of tool cmake found in PATH: 3.22.1. To use it, run '/usr/bin/python3
```

since WSLENV is not related for the esp-idf build environment ([WSLENV ](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/)) I removed the empty vars.

**Comment by kdschlosser** [comment]
and removing the empty variables corrects the error? I am running under WSL as well and I have not experienced that error at all. I would have to check and see if that is even set in my environment.

**Comment by kdschlosser** [comment]
Mine is not empty

```shell
WSLENV=WT_SESSION:WT_PROFILE_ID:
```

**Comment by kdschlosser** [comment]
from looking it seems that there are only 4 things that get set in the environment.
IDF_TOOLS_EXPORT_CMD
IDF_TOOLS_INSTALL_CMD
PATH
IDF_PATH

so maybe just checking for is the best thing.

**Comment by cheops** [comment]
the conclusion from the error and the solution I propose in this pull request was wrong.

the error is `/bin/sh: 22: ./export.sh: [[: not found`
this comes from the command `['. ./export.sh']` which gets executed with python like this
```
    p = subprocess.Popen(
        cmd_,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=True,
        env=env
    )
```
`shell=True` uses the default shell (which is `/bin/sh` on my default WSL Ubuntu)  
this is fine for the install.sh script which has a shebang `#!/usr/bin/env bash` but export.sh does not have this shebang  
the commands in `export.sh` are bash specific, so we should source the script with `/usr/bin/bash`

Aditionally, after `install` one should run `export`  
(this might solve the problem that the first build fails and only the second one succeeds)


Fixed in my latest commit.

**Comment by kdschlosser** [comment]
if there is no shebang in the export script then that is a bug upstream on not in my code. It needs to be fixed at the ESP-IDF level.

The problem with using the shell=True is it might fix it for linux but it will break running on Windows. While I know that running on Windows is not currently supported yet I would like to get it to compile on Windows at some point. Now I now that compiling under cygwin or mingw might not have an issue with the shell=True but if it is possible to do a compilation running under cmd.exe then there would be an issue. It has to do with how subprocess works and calling cmd.exe. 

I know enough Linux to get myself into trouble. But shouldn't we be able to specifically run bash and then send the commends into the process using subprocess.PIPE on stdin?

like this..


```python

if sys.platform.startswith('win'):
    shell = 'cmd.exe'
else:
    shell = 'bash'

p = subprocess.Popen(
        shell,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        stdin=subprocess.PIPE,
        env=env
    )
p.stdin.write(cmd_.encode('utf-8') + b'\n')
p.stdin.close()
```

That should work to solve the issue I would think.

Since you found the problem with the shebang in the export script you should open an issue with espressif for the ESPIDF. Make sure you specifically mention version 5.0.2 because that is what is supported in MicroPython. It really applies to all versions of the ESPIDF, I believe they are still doing bug fixes for 5.0.x and above.

If you manually ass the shebang to the export script does it compile properly?

Also I wanted to note the issue with having to run the make.py script a second time has to do with MicroPython build system and it not installing all of the dependencies properly. I have to look into it more to see what is going on. It does currently build so fixing that specific issue is not of top priority.

I am working on writing SDL drivers that works with the driver framework I have written. The way that LVGL handles the SDL drivers I am not able to use them. I want a user to be able to use the linux port for fast development and be able to upload the same source files without having to change anything and have it work on an MCU.

**Comment by cheops** [comment]
Hello,
let me first say: I really appreciate the time you are putting into this.

there is a note in the esp-idf documentation when running the export script under non-bash shells:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/tools/idf-tools.html#export-scripts

```
export.sh may be used with shells other than Bash (such as zsh).  
However, in this case, it is required to set the IDF_PATH environment variable before running the script.
When used in Bash, the script guesses the IDF_PATH value from its own location.
```

aditionally sourcing a script with a shebang is not possible: https://unix.stackexchange.com/questions/291541/can-i-use-a-shebang-to-have-a-file-source-itself-into-current-bash-environment

**Comment by kdschlosser** [comment]
Well isn't that an interesting conundrum. The export script is what sets the IDF_PATH variable but the script will not always function properly if the IDF_PATH variable is not set before the script runs.....


I have recently made some changes to the master branch that should solve the issue. It sets the IDF_PATH to the environment that export runs in. Hopefully that should solve the problem. I also updated the version of Micropython to the latest release and I updated the code so it will always use the latest master branch code of LVGL when building.

There are other fixes as well that I have committed, like needing to run the submodules command twice in order to get all the submodules to install properly. and I also fixed the crashing that occurs in the bus drivers. The RGBBus driver now works as it should. It requires using 2 buffers at the moment and that will be fixed in a couple of days as I do know how to go about fixing it,

I still have to work through a couple of issues with the indev drivers. that is going to take me a few days to figure out why it is hanging. It is going to be something pretty dumb I am sure.

**Comment by kdschlosser** [comment]
I want to say that I do appreciate the work and research you are putting in to find the best solution to this problem. I believe that the issue you are having with empty environment variables is a symptom and removing those variables is only a band-aide, we all know what happens to band-aides, they eventually fall off and can cause a different problem.

The drilling down to find the root of the problem is going to allow a fix that isn't going to fall off. I am hoping that the new information you have found is going to do this. I have applied the fix to the master branch, So now it needs to be tested and once it tests out as working I am going to comment the fix identifying you as the person that did the research and found the solution.

**Comment by kdschlosser** [comment]
I will add the comments to the file giving you the credit for locating the solution. 
Thank you for testing it.

**Comment by cheops** [comment]
I again get an error from line:
https://github.com/kdschlosser/lvgl_micropython/blob/main/builder/esp32.py#L664
seems the `export IDF_PATH` is missing there

**Comment by cheops** [comment]
I again get an error from line:
https://github.com/kdschlosser/lvgl_micropython/blob/main/builder/esp32.py#L664
seems the `export IDF_PATH` is missing there

**Comment by kdschlosser** [comment]
I figured out what the issue is and I am trying to correct it. It's because of shell=True in subprocess and it using sh as the shell and not bash. The export.sh script in the espidf doesn't have the bash tag at the top and that is because the script is not design to be run per se, it is supposed to be sourced. 

Which for the life of me I cannot remember how to do that. `source .export.sh` or is it `source . ./export.sh` I cannot remember.

**Comment by kdschlosser** [comment]
I am getting a hammering trying to get things to compile on a CI because there isn't a typical environment that is used. There are no "PATH" environment variables. they are written to files. It's crazy github actions does it. I am almost to the point of switching over to aszure devops if I knew that it wasn't designed this way. Last time I used it it wasn't.

**Comment by cheops** [comment]
> Which for the life of me I cannot remember how to do that. `source .export.sh` or is it `source . ./export.sh` I cannot remember.

`source <filename>` is bash equivalent for `. <filename>` (dot space filename)
https://ss64.com/bash/source.html
`. ./<filename>` (dot space dot slash filename) is to use filename from the current dir and not search in path

so I think that `cd <path_to_export.sh>`   `. ./export.sh` is the most portable way

**Comment by kdschlosser** [comment]
I have the export in place and I am calling `. ./export.sh` and the result is this error...

```
/bin/sh: 22: ./export.sh: [[: not found
```

I am setting the IDF_PATH but that error still persists. I think it is because the script is a bash script but it is being run in sh. I don't know why the subprocess is ignoring the SHELL= environment variable but it is. On my system SHELL is set to `/bin/bash` but it is completely ignored. If I manually set the subprocess to run bash the script hands on the call to export.sh and then terminates.

**Pull request closed without merging**
